doqfy/doqfy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("shorten/", include("shorten.urls", namespace="shorten")),
    path("shareme/", include("shareme.urls", namespace="shareme")),
    path("admin/", admin.site.urls),
]

doqfy/shareme/urls.py
from django.urls import path

from . import views

app_name = "shorten"
urlpatterns = [path("", views.index, name="index"), path("<str:snippet_id>/", views.get_snippet, name="snippet"),]

doqfy/shorten/urls.py
from django.urls import path

from . import views

app_name = "shorten"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:short_id>/", views.redirect_to_long_url, name="shortener-redirect"),
]

doqfy/shareme/models.py
from django.db import models


class Snippet(models.Model):
    snippet_id = models.CharField(primary_key=True, max_length=20)
    snippet = models.TextField()
    encrypted = models.BooleanField(default=False)
    salt = models.BinaryField(max_length=16, default=None, null=True)

    def __str__(self) -> str:
        return f"Snippet(snippet_id={self.snippet_id}, snippet={self.snippet}, encrypted={self.encrypted})"

doqfy/shorten/models.py
from django.db import models


class Url(models.Model):
    short_id = models.CharField(primary_key=True, max_length=20)
    long_url = models.TextField(db_index=True)

    def __str__(self) -> str:
        return f"{self.long_url} ({self.short_id})"

doqfy/shareme/views.py
from typing import Any

from django.http import HttpRequest, QueryDict
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .services import DecryptionError, SnippetCreationError, SnippetNotFoundError, SnippetService


def index(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        return create_shareable_link(request)

    context: dict[str, str] = {}
    if link := request.GET.get("link"):
        context["link"] = link

    return render(request, "index.html", context)


def get_snippet(request: HttpRequest, snippet_id: str) -> HttpResponse:
    key = None
    if request.method == "POST":
        # Encryption key.
        key = request.POST.get("key", None)

    share_service = SnippetService()
    try:
        snippet, encrypted = share_service.get_snippet(snippet_id, key)
        context = {"snippet": snippet, "encrypted": encrypted, "snippet_id": snippet_id}

        return render(request, "snippet.html", context)
    except SnippetNotFoundError:
        return render(request, "not-found.html")
    except DecryptionError:
        context = {"encrypted": True, "snippet_id": snippet_id, "error_message": "Invalid encryption key."}

        return render(request, "snippet.html", context)


def create_shareable_link(request: HttpRequest) -> HttpResponse:
    context: dict[str, str] = {}

    snippet = request.POST.get("snippet", None)
    if not snippet:
        context["error_message"] = "Please provide a snippet."

        return render(request, "index.html", context)

    base_url = request.build_absolute_uri()
    key = request.POST.get("key", None)
    share_service = SnippetService()

    try:
        link = share_service.add_and_get_shareable_link(snippet, base_url, key)

        return HttpResponseRedirect(_get_route_with_query_params("shareme:index", {"link": link}))
    except SnippetCreationError:
        context["error_message"] = "Something went wrong! Please try again later."

        return render(request, "index.html", context)


def _get_route_with_query_params(viewname: str, query_params: dict[str, Any]) -> str:
    query_dict = QueryDict("", True)
    query_dict.update(query_params)

    base_url = reverse(viewname)

    return f"{base_url}?{query_dict.urlencode()}"

doqfy/shorten/views.py
from typing import Any

from django.core.exceptions import ValidationError
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.http.request import HttpRequest
from django.shortcuts import render
from django.urls import reverse

from .services import InvalidUrlError, LongUrlNotFoundError, ShortenerService, ShortIdGenerationError


def index(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        return shorten_url(request)

    context: dict[str, str] = {}
    if long_url := request.GET.get("long_url"):
        if short_url := request.GET.get("short_url"):
            context["long_url"] = long_url
            context["short_url"] = short_url
        else:
            raise ValidationError("`short_url` must be provided if `long_url` is provided")

    return render(request, "shorten.html", context)


def redirect_to_long_url(request: HttpRequest, short_id: str) -> HttpResponse:
    shortener = ShortenerService()
    try:
        long_url = shortener.get_long_url(short_id)

        return HttpResponseRedirect(long_url)
    except LongUrlNotFoundError:
        return render(request, "not-found.html")


def shorten_url(request: HttpRequest) -> HttpResponse:
    long_url = request.POST["long_url"]

    if not long_url:
        return render(request, "shorten.html", context={"error_message": "Please enter some value for the URL."})

    base_url = request.build_absolute_uri()
    context: dict[str, str] = {"long_url": long_url}

    try:
        shortener = ShortenerService()
        short_url = shortener.get_short_url(long_url, base_url)

        return HttpResponseRedirect(
            _get_route_with_query_params("shorten:index", {"long_url": long_url, "short_url": short_url})
        )

    except ShortIdGenerationError:
        context["error_message"] = "Sorry! Failed to generate a unique short ID for the given URL."

        return render(request, "shorten.html", context)
    except InvalidUrlError:
        context["error_message"] = "Please enter a valid URL."

        return render(request, "shorten.html", context)


def _get_route_with_query_params(viewname: str, query_params: dict[str, Any]) -> str:
    query_dict = QueryDict("", True)
    query_dict.update(query_params)

    base_url = reverse(viewname)

    return f"{base_url}?{query_dict.urlencode()}"

doqfy/shareme/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shorten</title>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio"></script>
</head>

<body class="bg-red-800">
    {% block body %} {% endblock body %}
</body>

</html>

doqfy/shareme/templates/index.html
{% extends "base.html" %}


{% block body %}

  <div class="flex justify-center h-screen items-center">

    {% if link %}
    
      <div class="bg-white shadow-lg rounded-md p-10 sm:min-w-[500px] sm:max-w-[500px]">

    {% else %}

      <div class="bg-white shadow-lg rounded-md p-10 sm:min-w-[800px] sm:max-w-[800px]">

    {% endif %}

      <h1 class="text-3xl font-medium text-center">ShareMe</h1>

      <p> LINK: {{ link }}</p>

      {% if link %}

        <div class="flex flex-col mt-3">
          <label for="long-url" class="font-medium text-sm inline-flex gap-x-1 items-center">
            <svg class="size-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 0 1 1.242 7.244l-4.5 4.5a4.5 4.5 0 0 1-6.364-6.364l1.757-1.757m13.35-.622 1.757-1.757a4.5 4.5 0 0 0-6.364-6.364l-4.5 4.5a4.5 4.5 0 0 0 1.242 7.244" />
            </svg>
            <span>Link</span>
          </label>

          <input type="text" disabled id="snippet-url" name="snippet_url" value="{{ link }}" class="rounded-md bg-gray-100 border-none"/>
        </div>

        <div class="flex mt-4 justify-around">
           <a href="{{ link }}" class="inline-flex items-center gap-x-1 p-2 rounded-md border hover:bg-gray-200">
            <svg class="size-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
            </svg>
            <span>Visit URL</span>
          </a>

          <button type="button" class="inline-flex items-center gap-x-1 p-2 rounded-md border hover:bg-gray-200" onclick="copySnippetLinkToClipboard()">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
            </svg>
            <span>Copy</span>
          </button>

      </div>

      <div class="flex justify-center mt-3">
        <a href="{% url 'shareme:index' %}" class="bg-green-600 rounded-md p-2 font-medium text-lg text-white hover:bg-green-700">Generate Another Link</a>
      </div>


      {% else %}

        <p class="text-center mt-1">Enter a snippet and share it with anyone!</p>

        <form class="flex flex-col gap-y-3" method="post" action="{% url 'shareme:index' %}">

          {% csrf_token %}

          <div class="flex flex-col">
            <label for="snippet" class="inline-flex gap-x-1 items-center font-medium">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="m7.848 8.25 1.536.887M7.848 8.25a3 3 0 1 1-5.196-3 3 3 0 0 1 5.196 3Zm1.536.887a2.165 2.165 0 0 1 1.083 1.839c.005.351.054.695.14 1.024M9.384 9.137l2.077 1.199M7.848 15.75l1.536-.887m-1.536.887a3 3 0 1 1-5.196 3 3 3 0 0 1 5.196-3Zm1.536-.887a2.165 2.165 0 0 0 1.083-1.838c.005-.352.054-.695.14-1.025m-1.223 2.863 2.077-1.199m0-3.328a4.323 4.323 0 0 1 2.068-1.379l5.325-1.628a4.5 4.5 0 0 1 2.48-.044l.803.215-7.794 4.5m-2.882-1.664A4.33 4.33 0 0 0 10.607 12m3.736 0 7.794 4.5-.802.215a4.5 4.5 0 0 1-2.48-.043l-5.326-1.629a4.324 4.324 0 0 1-2.068-1.379M14.343 12l-2.882 1.664" />
              </svg>
              <span>Snippet</span>
            </label>
            <textarea required id="snippet" name="snippet" class="rounded-md bg-gray-100 border-none" rows="5"></textarea>
          </div>

          <div class="flex flex-col mt-2">
            <label for="key" class="inline-flex items-center gap-x-1 font-medium">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
              </svg>
              <span>Encryption Key</span>
            </label>
            <input type="password" id="key" name="key" placeholder="Enter the key to encrypt with" class="rounded-md bg-gray-100 border-none"/>        
          </div>

          {% if error_message %}
            <p class="text-red-500 font-medium text-center">{{ error_message }}</p>
          {% endif %}

          <div class="flex justify-center">
            <button type="submit" class="bg-green-600 rounded-md p-3 font-medium text-lg text-white max-w-40 hover:bg-green-700">Generate Link</button>
          </div>
          
        </form>
      {% endif %}
      
    </div>


  </div>

  <div class="absolute bottom-0 mr-5 mb-5 right-0 opacity-0 transition-opacity" id="success-alert">
    <div class="flex items-center p-4 mb-4 text-sm text-green-200 rounded-lg bg-green-800" role="alert">
      <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
      </svg>
      <span class="sr-only">Info</span>
      <div>
        <span class="font-medium">Success!</span> Copied the URL to the clipboard.
      </div>
    </div>
  </div>

  <script>

      function copySnippetLinkToClipboard() {
      const element = document.getElementById("snippet-url");
      if (!element) {
        return;
      }

      navigator.clipboard.writeText(element.value);      

      const successAlert = document.getElementById("success-alert");
      if (!successAlert) {
        return;
      }
      successAlert.classList.add("opacity-100");

      window.setTimeout(hideSuccessAlert, 2500);
    }

    function hideSuccessAlert() {
      const successAlert = document.getElementById("success-alert");
      if (!successAlert) {
        return;
      }
      successAlert.classList.remove("opacity-100");

    }

  </script>


{% endblock body %}

doqfy/shareme/templates/not-found.html
{% extends "base.html" %}


{% block body %}

  <div class="flex justify-center h-screen items-center">

    <div class="flex flex-col gap-y-3 border p-10 shadow-md bg-white rounded-md min-w-48 items-center">

      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
        <path fill-rule="evenodd" d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003ZM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75Zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z" clip-rule="evenodd" />
      </svg>
      <h1 class="text-3xl font-medium">404 Not Found</h1>
      <p>This URL does not exist.</p>

      <a href="{% url 'shorten:index' %}" class="mt-4 px-2 mb-1 bg-green-600 rounded-md text-white py-2 font-medium hover:bg-green-700">Go to Home Page</a>
    </div>

  </div>
{% endblock %}

doqfy/shareme/templates/snippet.html
{% extends "base.html" %}


{% block body %}

  <div class="flex justify-center h-screen items-center">

    <div class="bg-white shadow-lg rounded-md p-10 sm:min-w-[800px] sm:max-w-[800px] flex flex-col">

      <h1 class="text-3xl font-medium text-center">ShareMe</h1>
  
      {% if encrypted %}
  
        <p class="text-center mt-3">The snippet is encrypted. Please enter the key that it was encrypted with.</p>
  
        <form class="flex flex-col gap-y-3" method="post" action="{% url 'shareme:snippet' snippet_id=snippet_id %}">

          {% csrf_token %}

          <div class="flex flex-col mt-2">
            <label for="key" class="inline-flex items-center gap-x-1 font-medium">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
              </svg>
              <span>Encryption Key</span>
            </label>
            <input type="password" id="key" name="key" placeholder="Enter the key to encrypt with" class="rounded-md bg-gray-100 border-none"/>        
          </div>

          {% if error_message %}
            <p class="text-red-500 font-medium text-center">{{ error_message }}</p>
          {% endif %}

          <div class="flex justify-center">
            <button type="submit" class="bg-green-600 rounded-md p-3 font-medium text-lg text-white max-w-40 hover:bg-green-700">Decrypt</button>
          </div>
        </form>
  
      {% else %}
        <div class="flex flex-col">
          <div class="inline-flex gap-x-1 items-center font-medium">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
              <path stroke-linecap="round" stroke-linejoin="round" d="m7.848 8.25 1.536.887M7.848 8.25a3 3 0 1 1-5.196-3 3 3 0 0 1 5.196 3Zm1.536.887a2.165 2.165 0 0 1 1.083 1.839c.005.351.054.695.14 1.024M9.384 9.137l2.077 1.199M7.848 15.75l1.536-.887m-1.536.887a3 3 0 1 1-5.196 3 3 3 0 0 1 5.196-3Zm1.536-.887a2.165 2.165 0 0 0 1.083-1.838c.005-.352.054-.695.14-1.025m-1.223 2.863 2.077-1.199m0-3.328a4.323 4.323 0 0 1 2.068-1.379l5.325-1.628a4.5 4.5 0 0 1 2.48-.044l.803.215-7.794 4.5m-2.882-1.664A4.33 4.33 0 0 0 10.607 12m3.736 0 7.794 4.5-.802.215a4.5 4.5 0 0 1-2.48-.043l-5.326-1.629a4.324 4.324 0 0 1-2.068-1.379M14.343 12l-2.882 1.664" />
            </svg>
            <span>Snippet</span>
          </div>
          <div class="rounded-md bg-gray-100 border-none p-1 min-h-[100px] cursor-pointer" onclick="copySnippetToClipboard()"><p id="snippet">{{ snippet }}</p></div>
        </div>
  
        <a class="mt-4 mb-1 bg-green-600 rounded-md text-white py-2 font-medium hover:bg-green-700 text-center" href="{% url 'shareme:index' %}">
          Go Home
        </a>
  
      {% endif %}
  
  
    </div>
  </div>

  <div class="absolute bottom-0 mr-5 mb-5 right-0 opacity-0 transition-opacity" id="success-alert">
    <div class="flex items-center p-4 mb-4 text-sm text-green-200 rounded-lg bg-green-800" role="alert">
      <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
      </svg>
      <span class="sr-only">Info</span>
      <div>
        <span class="font-medium">Success!</span> Copied the snippet to the clipboard.
      </div>
    </div>
  </div>

  <script>

      function copySnippetToClipboard() {
      const element = document.getElementById("snippet");
      if (!element) {
        return;
      }

      navigator.clipboard.writeText(element.innerText);      

      const successAlert = document.getElementById("success-alert");
      if (!successAlert) {
        return;
      }
      successAlert.classList.add("opacity-100");

      window.setTimeout(hideSuccessAlert, 2500);
    }

    function hideSuccessAlert() {
      const successAlert = document.getElementById("success-alert");
      if (!successAlert) {
        return;
      }
      successAlert.classList.remove("opacity-100");

    }

  </script>

{% endblock body %}

doqfy/shorten/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shorten</title>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio"></script>
</head>

<body class="bg-gray-50">
    {% block body %} {% endblock body %}
</body>

</html>

doqfy/shorten/templates/not-found.html
{% extends "base.html" %}


{% block body %}

  <div class="flex justify-center h-screen items-center">

    <div class="flex flex-col gap-y-3 border p-10 shadow-md bg-white rounded-md min-w-48 items-center">

      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
        <path fill-rule="evenodd" d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003ZM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75Zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z" clip-rule="evenodd" />
      </svg>
      <h1 class="text-3xl font-medium">404 Not Found</h1>
      <p>This URL does not exist.</p>

      <a href="{% url 'shorten:index' %}" class="mt-4 px-2 mb-1 bg-green-600 rounded-md text-white py-2 font-medium hover:bg-green-700">Go to Home Page</a>
    </div>

  </div>
{% endblock %}